apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: microservice
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: microservice
      tier: frontend
  template:
    metadata:
      labels:
        app: microservice
        tier: frontend
    spec:
      containers:
      - name: code
        image: batesjo/microservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000